// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXbCzVZ9dlwssZJXxLn40hFIvAwcR2zvk',
    appId: '1:919706067803:android:87f872a61a4330ec7fb07e',
    messagingSenderId: '919706067803',
    projectId: 'fir-fortest-6dd5f',
    storageBucket: 'fir-fortest-6dd5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAntBAP9zVViXtLII2EojRItKxUXbMk0Ug',
    appId: '1:919706067803:ios:2654b53f9d9c6ee37fb07e',
    messagingSenderId: '919706067803',
    projectId: 'fir-fortest-6dd5f',
    storageBucket: 'fir-fortest-6dd5f.appspot.com',
    androidClientId: '919706067803-fg8kbpbf07uu403astf8psmpjdsqflem.apps.googleusercontent.com',
    iosClientId: '919706067803-3ur1rdu9gbcnavhnmmonlqgnqdb8rnc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopping',
  );
}
